### ISSUE TITLE
Question: How to get the activity result from a fragment?

### ISSUE THREAD

**Issue by emanzanoaxa** [aartikov/Alligator#10]
I've been searching how to get the activity result from a Fragment on the docs and on the examples but I cannot find how to do it. I've successfully retrieved the activity result from an activity, but I don't see the way to get it directly from a fragment.

Is possible to get the result from a fragment instead of its parent activity? Can you give me some hints to do it?

Thanks.

**Comment by aartikov** [comment]
A result is handled by `ScreenResultListener` in an activity. There are no other options in the library. But you can pass a result manually anywhere you want. For example, to the current fragment (if it implements `ScreenResultListener`):

```java
@Override 
public void onScreenResult(Class<? extends Screen> screenClass, @Nullable ScreenResult result) {
	FragmentManager fragmentManager = activity.getSupportFragmentManager();
	Fragment fragment = fragmentManager.findFragmentById(containerId);
	if (fragment instanceof ScreenResultListener) {
		((ScreenResultListener) fragment).onScreenResult(screenClass, result);
	}
}
```
