### ISSUE TITLE
Handle result if activity is destroyed

### ISSUE THREAD

**Issue by AlexisQapa** [aartikov/Alligator#11]
Hi,

Would this lib allow a result to be passed across multiple activities like : 
A need result D produce result But B is destroyed by android
A -> B (destroyed) -> C -> D

**Comment by aartikov** [comment]
No, it doesn't. Alligator uses `startActivityForResult` and `setResult` to pass a result. So a result can be returned to a previous activity only.

**Comment by AlexisQapa** [comment]
So there is no way build build something like goBackToWithResult ?

the flag Intent.FLAG_ACTIVITY_FORWARD_RESULT allow to forward a result to the parent of the parent if the parent if finished.

**Comment by aartikov** [comment]
I suppose it is possible. I will think this through.

**Comment by AlexisQapa** [comment]
I found that this flag also have its flaws as depending of activities count in the flow it's hard to manage something that always works. I have another lead though we can always start activities for results, as I think this is what you already do, and always finish if result is ok but not handled.
`handleResult() else if (resultCode == RESULT_OK) {
            // If there is a result but we can't handle it, we should be in a flow so stop and pass the result to child
            setResult(resultCode, data)
            finish()
        }`

what do you think about this ?

**Comment by aartikov** [comment]
Thank you for the good ideas.
Passing result by chain will likely work, but it will require significant changes in a library. I don't start every activity for result, just activities that are registered appropriately. I also use request codes to identify how to retrieve a result from an intent.

So I decided to pass a result directly from the last activity to the first one in the chain through `onNewIntent` callback. It works fine. I push my current progress to this branch https://github.com/aartikov/Alligator/tree/feature/go-back-to-with-result
I will recheck if everything is ok and make a release soon.

**Comment by AlexisQapa** [comment]
Nice job on the branch ! One thing thought, I think on newIntent is not called if the activity was destroyed and the intent would be passed in onCreate. So both methods should call the code that handle the resutlt according to http://www.helloandroid.com/tutorials/communicating-between-running-activities. It's an old link but I didn't found any thing clearer than this.

**Comment by aartikov** [comment]
No, result handling should not be called in onCreate, because getIntent() will return an intent that started an activity, but not the one that was used to go back to it.
I assume that nobody will `goBackTo` or `goBackToWithResult` to the screen that is not present in the stack. It would be ideally to get `ScreenNotFoundException` in that case (as it happens with fragment screens), but I have not found a way to implement it reliably for activities.

**Comment by Alex293** [comment]
While I understand you point I still think that an activity can be in the back stack and been killed then recreated

**Comment by aartikov** [comment]
I have checked that `onNewIntent` is called even if an activity has been recreated.

**Comment by aartikov** [comment]
Version 2.2.0 with this feature is released.
