### ISSUE TITLE
Nested fragment ScreenSwitcher

### ISSUE THREAD

**Issue by DomiBlaze** [aartikov/Alligator#12]
Is it possible to implement nested `FragmentScreenSwitcher`?
One of my fragments(let's call it `HostFragment`) has a bottom navigation implemented, and I want to use `switchTo` to switch betweed child fragments of `HostFragment`.
Furthermore, I have `AnotherHostFragment` with different set of fragments. 
I want to solve this problem without additional activities, in a single activity app setup. 

Thank you in advance

**Comment by aartikov** [comment]
You can extend `FragmentScreenSwitcher` to delegate switching of inner fragments to additional screen switchers. Like that:

```java
public interface ScreenSwitcherProvider {
	ScreenSwitcher getScreenSwitcher();
}
```
```java
public class MainScreenSwitcher extends FragmentScreenSwitcher {

	// constructors are ommited
	
	@Override
	public void switchTo(Screen screen, @Nullable AnimationData animationData) throws NavigationException {
		if (isInner(screen)) {
			ScreenSwitcher screenSwitcher = ((ScreenSwitcherProvider) getCurrentFragment()).getScreenSwitcher();
			screenSwitcher.switchTo(screen, animationData);
		} else {
			super.switchTo(screen, animationData);
		}
	}
}
```
