### ISSUE TITLE
Fragment BackStack Handling

### ISSUE THREAD

**Issue by RodrigoMRodovalho** [aartikov/Alligator#14]
Hello, Im trying to understand how can I achieve the fragment backstack handling. Im running the sample **advancedscreenswitchersample** but when I go though fragments and touch on back button it closes the app.

Im running on Nexus 5x - Android 8.1.0

Thanks.

**Comment by aartikov** [comment]
Switching between tabs is not stored in a backstack. This behavior corresponds to the [guidelines](https://material.io/design/components/bottom-navigation.html#behavior).

**Comment by RodrigoMRodovalho** [comment]
So, how can I get this behavior using FragmentScreenSwitcher ?

**Comment by aartikov** [comment]
Do you really need it?
FragmentScreenSwitcher does not have this functionality. You can store a list of recently visited tabs somewhere and switch between them on back button pressed.

**Comment by RodrigoMRodovalho** [comment]
Ok. I got it. I will think if it is really needed. Thank you for the quick reply and the material design reference.
