### ISSUE TITLE
Navigation tree

### ISSUE THREAD

**Issue by genaku** [aartikov/Alligator#15]
Artur, thanks for your library! I'm happy to use it since ver.1.0.
May be you'd met with this case and know how to solve it. 
For example application have complex screens structure.
A -> B -> С
|
v
D -> E
Current activity is C. Then application gets push-notification, user tap on it and application should open activity E. I.e. it goes from C to E. BUT when user tap on back from current activity (now it is E) it should go to D, and on next back - to A. Is it possible to solve the issue with your lib?

**Comment by aartikov** [comment]
Hi. I think, you can build an appropriate screen stack like that:
```
navigator.reset(new ScreenA());
navigator.goForward(new ScreenD());
navigator.goForward(new ScreenE());
```

**Comment by genaku** [comment]
Thank you!
