### ISSUE TITLE
In which case getScreen can return null ?

### ISSUE THREAD

**Issue by iandreyshev** [aartikov/Alligator#16]

**Comment by aartikov** [comment]
It is possible if you implement a custom [converter](https://github.com/aartikov/Alligator/blob/master/alligator/src/main/java/me/aartikov/alligator/functions/ActivityConverter.java) that returns null. The default converter throws an exception when something wrong happened.

**Comment by iandreyshev** [comment]
I have this exception
I get ScreenResolver from AndroidNavigator
When I call screenResolver.getScreen(). Returned screen is null and kotlin code throws NPE

![screenexception_2](https://user-images.githubusercontent.com/22149746/45486826-27ac8e00-b765-11e8-8620-da7a1e9fe970.PNG)
![screenexception_3](https://user-images.githubusercontent.com/22149746/45486827-27ac8e00-b765-11e8-9157-04c34f929c29.PNG)

Version of navigator is 1.0.0 =)

**Comment by aartikov** [comment]
It is hard to say what could have happened. Version 1.0.0 was released more than an year ago.
Is it a crash from your Crashlytics? Do you succeed to reproduce it?
Btw, I recommend you to use newer version of Alligator.

**Comment by iandreyshev** [comment]
@aartikov I don't can to reproduce
Ok. I think the best way is to put try-catch and update version of library

**Comment by aartikov** [comment]
Starting from Alligator 3.0.0 `getScreen` never returns null. It throws an exception if something goes wrong. There is also `getScreenOrNull(activity)` method now.
