### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by olegivo** [aartikov/Alligator#17]
Do you have plans to migrate this project to Kotlin?

**Comment by aartikov** [comment]
I don't plan just to rewrite the code from Java to Kotlin. It will not give some significant profit. Maybe I will use Kotlin in the case of big refactoring. 
The fact that Alligator is written in Java does not prevent you from using it with Kotlin. Java to Kotlin interop is great! But I plan to add more nullability annotation in the next release to fix some minor troubles. Stay tuned for updates.

**Comment by aartikov** [comment]
I added `@NonNull` and `@Nullable` annotations for better Kotlin support.
