### ISSUE TITLE
CurrentScreen

### ISSUE THREAD

**Issue by genaku** [aartikov/Alligator#2]
Is there possibility to know what current screen is now?

**Comment by aartikov** [comment]
There are no such methods as _getCurrentScreen_ in _Navigator_. You can only send commands to _Navigator_ but not qwery it for something.

You can set _TransitionListener_ using _NavigationContext_ to know when a current screen is changed:
```java
@Override
protected void onResumeFragments() {
    super.onResumeFragments();
    NavigationContext navigationContext = new NavigationContext.Builder(this)
            .transitionListener(yourTransitionListener)
            .build();
    mNavigationContextBinder.bind(navigationContext);
}
```

If you know what an activity or a fragment is current now you can get a screen from it using _ScreenResolver_.

**Comment by genaku** [comment]
Ok. Thank you!
