### ISSUE TITLE
screenResolver.getScreen() returns null

### ISSUE THREAD

**Issue by issa-h** [aartikov/Alligator#25]
Hi 👋,

Thank you for this great lib!

I have a problem when I try to get a the current activity Screen in the `onCreate()` of it. The `screenResolver` returns a null for the `.getScreen()` call curiously.

I have registered my Activity and it's corresponding Screen in the NavigationFactory.

Here is my Activity and Screen declaration :
```
class LoginActivity : BaseActivity() {
...
data class Screen(
        val myString: String? = null
    ): me.aartikov.alligator.Screen, Serializable
}
```

```
override fun onCreate(savedInstanceState: Bundle?) {
     screenResolver.getScreen(this) //returns null
}
```

Note that because I haven't migrate my app to AndroidX, I am currently on the version 2.2.0. That's why the #16 issue didn't help me a lot for the moment.

Have you any suggestion for me ?

Thank you in advance 👍

**Comment by aartikov** [comment]
Do you use  `Navigator` to start this screen?

**Comment by issa-h** [comment]
No, I don't, it's my LAUNCHER Activity

**Comment by issa-h** [comment]
I think I got my answer : Screens are not instantiated for Activities that are launched by the system right ?

**Comment by aartikov** [comment]
Yes, correct.
