### ISSUE TITLE
[Improvement] Make a new navigator method to keep already loaded Fragments.

### ISSUE THREAD

**Issue by emanzanoaxa** [aartikov/Alligator#3]
Hi, first of all thanks for this great lib!

It's too difficult to add a new navigation method that checks if a fragment is already loaded instead replacing it everytime?

**Comment by aartikov** [comment]
Hi. I suppose `switchTo` is the method you ask for. To make its calling posible you should to create a `FragmentScreenSwitcher`  instance and set it to `NavigationContext`. Also make sure that screens passed to `switchTo` method have `equals` and `hashCode` methods correctly overridden. Take a look at [this sample](https://github.com/aartikov/Alligator/tree/master/simplescreenswitchersample) and [this part of README](https://github.com/aartikov/Alligator#switch-screens) for more details.
